services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
    environment:
      TZ: Asia/Shanghai
      ENABLE_CJK_FONT: 1
    restart: unless-stopped